### ISSUE TITLE
Correct repository

### ISSUE THREAD

**Issue by PhKindermann** [alanctprado/pace2024#27]
Hey,
we received two submissions from your team: this repository and https://github.com/heittpr/pace2024 . Both seem to be the same solver. Which one should we use for the evaluation?
Best
Philipp

**Comment by alanctprado** [comment]
Hi!

We apologize for the misunderstanding. Our initial intention was to submit
a single solver, which would choose a different approach, either the
Dynamic Programming or the Integer Programming, based on characteristics of
the instance. However, we were not able to integrate both approaches on
time, so we split the repository in two. Each one has the release
`pace-2024`, as specified, on the git branch that contains the code for the
respective approach.

If you check the lines in [1], it can be viewed that alanctprado's
repository uses a BaseSolver class that itself instantiates an integer
programming solver. In [2], you can see that the heittpr's repository uses
a DP Solver directly. Although the repositories share a lot of files in
common, the program flow is entirely different for each approach. In fact,
the programs only share the input and output parsers and a few base
classes. It was a mistake on our part to submit the solvers the way we did.
Because it was done on short notice, the points I just explained are very
unclear.

We are working on describing each approach in different solver
descriptions. Could it be possible to evaluate both solvers? We are
interested in seeing the differences in the behaviour of each one. If not,
let me know, and we can choose one :)

Thank you!

[1]:
https://github.com/alanctprado/pace2024/blob/6d7dd854ec5c9f670166e262faba1f82483b32de/src/main.cpp#L32
[2]:
https://github.com/heittpr/pace2024/blob/60841d4edf0454b79d37b8727d0380d3a06cb369/src/main.cpp#L37

**Comment by PhKindermann** [comment]
No worries, we will of course judge both submissions! I was just confused :)
